# This is a GitHub workflow defining a set of jobs with a set of steps.
# ref: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
#
name: Refreeze Dockerfile's requirements.txt

on:
  push:
    paths:
      - "**/requirements.in"
      - "**/requirements.txt"
      - ".github/workflows/refreeze-dockerfile-requirements-txt.yaml"
    branches: ["main"]
    tags: ["**"]
  workflow_dispatch:

jobs:
  refreeze-dockerfile-requirements-txt:
    name: Refreeze Dockerfile's requirements.txt

    # Don't run this job on forks
    if: github.repository == 'jupyterhub/docker-image-cleaner'
    runs-on: ubuntu-latest

    environment: refreeze-dockerfile-requirements-txt

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Refreeze Dockerfile's requirements.txt based on requirements.in
        run: |
          cd ${{ matrix.image }}
          docker run --rm \
              --env=CUSTOM_COMPILE_COMMAND='Use "Run workflow" button at https://github.com/jupyterhub/docker-image-cleaner/actions/workflows/refreeze-dockerfile-requirements-txt.yaml' \
              --volume=$PWD:/io \
              --workdir=/io \
              --user=root \
              python:3.9-alpine \
              sh -c 'pip install pip-tools==6.* && pip-compile --upgrade'

      - name: git diff
        run: git --no-pager diff --color=always

      # ref: https://github.com/peter-evans/create-pull-request
      - name: Create a PR
        uses: peter-evans/create-pull-request@v4
        with:
          token: "${{ secrets.jupyterhub_bot_pat }}"
          author: JupyterHub Bot Account <105740858+jupyterhub-bot@users.noreply.github.com>
          committer: JupyterHub Bot Account <105740858+jupyterhub-bot@users.noreply.github.com>
          branch: update-image-requirements
          labels: dependencies
          commit-message: Refreeze Dockerfile's requirements.txt
          title: Refreeze Dockerfile's requirements.txt
          body: >-
            Dockerfile's requirements.txt has been refrozen based on
            requirements.in.
