name: Test

on:
  pull_request:
    paths-ignore:
      - "docs/**"
      - "**.md"
      - ".github/workflows/*"
      - "!.github/workflows/test.yaml"
  push:
    paths-ignore:
      - "docs/**"
      - "**.md"
      - ".github/workflows/*"
      - "!.github/workflows/test.yaml"
    branches-ignore:
      - "dependabot/**"
      - "pre-commit-ci-update-config"
    tags:
      - "**"
  workflow_dispatch:

env:
  # UTF-8 content may be interpreted as ascii and causes errors without this.
  LANG: C.UTF-8
  PYTEST_ADDOPTS: "--verbose --color=yes"

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-20.04
    timeout-minutes: 15

    strategy:
      matrix:
        python:
          - "3.10"

    steps:
      - uses: actions/checkout@v3

      # NOTE: actions/setup-python@v4 make use of a cache within the GitHub base
      #       environment and setup in a fraction of a second.
      - name: Install Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: "${{ matrix.python }}"

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install -e ".[test]"

      - name: List Python dependencies
        run: |
          pip freeze

      - name: Run pytest
        run: |
          pytest --maxfail=2 --cov=docker_image_cleaner tests

      - uses: codecov/codecov-action@v3
