name: Test

on:
  pull_request:
    paths-ignore:
      - "**.md"
      - ".github/workflows/*"
      - "!.github/workflows/test.yaml"
  push:
    paths-ignore:
      - "**.md"
      - ".github/workflows/*"
      - "!.github/workflows/test.yaml"
    branches-ignore:
      - "dependabot/**"
      - "pre-commit-ci-update-config"
    tags:
      - "**"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        include:
          - python-version: "3.8"
          - python-version: "3.11"

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "${{ matrix.python-version }}"

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install -e ".[test]"

      - name: List Python dependencies
        run: |
          pip freeze

      - name: Run pytest
        # if pytest is run without sudo, it won't have permissions to inspect
        # /var/lib/docker and can't decide on when to clean etc either.
        #
        # FIXME: docker image cleaner should realize it doesn't have permissions
        #        to estimate the disk usage in get_absolute_size
        #
        run: |
          sudo -E PATH=$PATH bash -c "pytest --maxfail=2 --cov=docker_image_cleaner"

      # GitHub action reference: https://github.com/codecov/codecov-action
      - uses: codecov/codecov-action@v3
